---
title: "Extracting Tables from PDF - Workshops for Ukraine :ukraine:"
format: gfm
echo: false
warning: false
message: false
---

# Instructions prior to the workshop

Here you will find instructions regarding files needed, package installation and program requirements for this workshop.

## Files needed

Please **clone this repository** so you can have the files we will be using during the workshop. 

In the "pdf" directory, you will find:

- A PDF file that we will use to extract a table using the `tabulizer` package.

- Another PDF file that we will use to extract a table using `tesseract`.

## R packages

Install the following R packages: `{tidyverse}` and `{tesseract}`.

```r
install.packages(tidyverse)
install.packages(tesseract)
```

If you encounter an error when installing `{tesseract}`, you might need to install three development libraries via the command line: `libtesseract-dev`, `libleptonica-dev` and `tesseract-ocr-eng`.

```bash
sudo apt-get install libtesseract-dev and libleptonica-dev tesseract-ocr-eng
```

Check the installation by loading the libraries:

```r
library(tidyverse)
library(tesseract)
```


## Program requirements

### Quarto
**Quarto** is required to render the documents. Please install using [this link](https://quarto.org/docs/get-started/).

### Docker
**Docker** is a required program for this workshop. Don't worry, it will be a simple use, nothing complicated. Please refer to the provided instructions available in PDF and Markdown formats for Windows, Mac, and Ubuntu, located in the `docker_instructions` directory.

- **Markdown version**: You can copy the code directly from GitHub, but note that the tutorial does not contain images.

- **PDF version**: Includes all images of the tutorial, but you will need to download the file of interest if you want to copy the code.





