---
title: "Installment requirements"
format: gfm
echo: false
warning: false
message: false
---

## Instructions prior to the workshop

In this file, you will find instructions regarding package installation and program requirements for this workshop.

## R packages

Install the following R packages: `{tidyverse}` and `{tesseract}`.

```r
install.packages(tidyverse)
```

```r
install.packages(tesseract)
```

If you encounter an error when installing `{tesseract}`, you might need to install three development libraries via the command line: `libtesseract-dev`, `libleptonica-dev` and `tesseract-ocr-eng`.

```bash
sudo apt-get install libtesseract-dev and libleptonica-dev tesseract-ocr-eng
```

Check the installation by loading the libraries:

```{r}
library(tidyverse)
library(tesseract)
```


## Docker

Please refer to the provided instructions available in PDF and Markdown formats for Windows, Mac, and Ubuntu, located in the respective directories.

- **Markdown version**: You can copy the code directly from GitHub, but note that it does not contain images.

- **PDF version**: Includes all images, but you will need to download the files separately if you want to copy the code.



